[otel]
environment = "dev"
log_user_prompt = false

[otel.exporter.otlp-http]
endpoint = "http://localhost:8200/v1/logs"
protocol = "binary"

[otel.trace_exporter.otlp-http]
endpoint = "http://localhost:8200/v1/traces"
protocol = "binary"

[otel.metrics_exporter.otlp-http]
endpoint = "http://localhost:8200/v1/metrics"
protocol = "binary"
